apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-simulator-appset
  namespace: openshift-gitops
spec:
  project: mqtt  
  source:
    repoURL: 'https://github.com/sumicsamy/mqtt.git'       # your repo
    targetRevision: main                                   # branch
    path: fleet-sim/fleet_sim_chart                        # path to the Helm chart
    helm:
      valueFiles:
        - values.yaml                                      # optional override
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
