apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-simulator-appset
  namespace: openshift-gitops
spec:
  project: fleet-simulator  
  source:
    repoURL: 'https://github.com/sumicsamy/mqtt.git'       # your repo
    targetRevision: main                                   # branch
    path: fleet-sim/fleet_sim_chart                        # path to the Helm chart
    helm:
      valueFiles:
        - values.yaml                                      # optional override
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fleet-simulator
  namespace: openshift-gitops
spec:
  description: Project to manage all fleet truck simulator Applications
  sourceRepos:
    - 'https://github.com/sumicsamy/mqtt.git'
    - 'https://charts.jetstack.io'
    - 'https://repos.emqx.io/charts'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'