apiVersion: apps/v1
kind: Deployment
metadata:
  name: truck-sim
  labels:
    app: truck-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truck-sim
  template:
    metadata:
      labels:
        app: truck-sim
    spec:
      serviceAccountName: truck-sim-sa
      containers:
      - name: truck-sim
        image: quay.io/suchugh/fleet-sim:0.0.5
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: truck-sim-config
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "1Gi"
