apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: emqx-anyuid
subjects:
  - kind: ServiceAccount
    name: default               # EMQX pods use this SA by default
    namespace: emqx             # namespace where EMQX runs
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
   name: emqx
spec:
  clusterDomain: cluster.local
  config:
    mode: Merge
  coreTemplate:
    metadata: {}
    spec:
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /status
          port: dashboard
        initialDelaySeconds: 60
        periodSeconds: 30
      readinessProbe:
        failureThreshold: 12
        httpGet:
          path: /status
          port: dashboard
        initialDelaySeconds: 10
        periodSeconds: 5
      replicas: 2
      resources: {}
      volumeClaimTemplates:
        resources: {}
  image: 'emqx/emqx:5.8.8'
  updateStrategy:
    evacuationStrategy:
      connEvictRate: 1000
      sessEvictRate: 1000
      waitTakeover: 10
    initialDelaySeconds: 10
    type: Recreate
