# How many Telegraf instances you want
size: 22   # e.g., 30 pods, adjust based on testing

# Shared subscription groups (3 queues)
sharedGroups:
  - telegraf-g0
  - telegraf-g1
  - telegraf-g2
  - telegraf-g3
  - telegraf-g4
  - telegraf-g5
  - telegraf-g6
  - telegraf-g7
  - telegraf-g8
  - telegraf-g9
  - telegraf-g10
  - telegraf-g11