---    
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: fleet-manager-broker
  namespace: mqtt-broker
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  adminUser: admin
  adminPassword: admin
  acceptors:
    - name: mqtts
      protocols: mqtt
      port: 8883
      sslEnabled: true
      needClientAuth: true
      verifyHost: false
      sslSecret: amq-broker-tls
      trustSecret: fleet-root-trust
      suppressInternalManagementObjects: true
      trustStoreType: PEMCA
      sslProvider: OPENSSL
      enabledProtocols: TLSv1.2,TLSv1.3
      enabledCipherSuites: TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384
  brokerProperties:
    - "acceptorConfigurations.mqtts.params.sslAutoReload=true"
    - brokerPlugins.\"org.apache.activemq.artemis.core.server.plugin.impl.LoggingActiveMQServerPlugin.class\".init=LOG_CONNECTION_EVENTS=false,LOG_SESSION_EVENTS=false,LOG_CONSUMER_EVENTS=true
  env:
    - name: TZ
      value: Australia/Melbourne
    - name: JDK_JAVA_OPTIONS
      value: -XshowSettings:system
    - name: JAVA_ARGS_APPEND
      value: -Dhawtio.realm=console  
  deploymentPlan:
    size: 3
    persistenceEnabled: true
    clustered: true
    journalType: nio
    enableMetricsPlugin: true
    storage:
      size: 10Gi
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "20Gi"
        cpu: "5000m"
    extraMounts:
      secrets:
      - "fleet-manager-broker-jaas-config"
      - "site-roles-bp"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: ActiveMQArtemis
                  operator: In
                  values:
                    - fleet-manager-broker
            topologyKey: kubernetes.io/hostname
  console:
    expose: true
  