---    
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: fleet-manager-broker
  namespace: mqtt-broker
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acceptors:
    - name: mqtts
      protocols: mqtt
      port: 8883
      sslEnabled: true
      needClientAuth: true
      verifyHost: false
      sslSecret: amq-broker-tls
      trustSecret: fleet-root-trust
      suppressInternalManagementObjects: true
      trustStoreType: PEMCA
      sslProvider: OPENSSL
      enabledProtocols: TLSv1.2,TLSv1.3
      enabledCipherSuites: TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384
  brokerProperties:
    - "acceptorConfigurations.mqtts.params.sslAutoReload=true"
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    clustered: false
    journalType: nio
    enableMetricsPlugin: true
    extraMounts:
      secrets:
      - "amq-jaas-cert-login"
      - "site-roles"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: ActiveMQArtemis
                  operator: In
                  values:
                    - fleet-manager-broker
            topologyKey: kubernetes.io/hostname
  console:
    expose: true
  