---
# amq-broker-operator/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: mqtt-broker
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---    
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: fleet-manager-broker
  namespace: mqtt-broker
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acceptors:
    - name: mqtts
      protocols: mqtt
      port: 8883
      sslEnabled: true
      needClientAuth: false
      sslSecret: amq-broker-tls
  deploymentPlan:
    size: 2
    persistenceEnabled: true
    journalType: nio
  console:
    expose: true
  security:
    authentication:
      enabled: true
      user: admin
      password: admin
      roles: admin
    authorization:
      - match: "mine.#"
        permissions:
          - operationType: createNonDurableQueue
            roles: [ "admin", "anonymous" ]
          - operationType: createAddress
            roles: [ "admin", "anonymous" ]
          - operationType: send
            roles: [ "admin", "anonymous" ]
          - operationType: consume
            roles: [ "admin", "anonymous" ]
          - operationType: browse
            roles: [ "admin", "anonymous" ]
