resources:
  - operator.yaml
  - amq-broker.yaml
  - service.yaml


secretGenerator:
- name: amq-broker-tls
  namespace: mqtt-broker 
  files:
    - broker.ks=ssl/broker.ks
  literals:
    - KEYSTORE_PASSWORD=changeit
  type: Opaque

generatorOptions:
  disableNameSuffixHash: true  