apiVersion: v1
kind: Service
metadata:
  name: mqtt-lb
  namespace: mqtt-broker
spec:
  selector:
    ActiveMQArtemis: fleet-manager-broker
  ports:
    - port: 8883
      name: mqtt
      targetPort: 8883
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mqtt-lb
  namespace: mqtt-broker
spec:
  port:
    targetPort: 8883
  to:
    kind: Service
    name: mqtt-lb
    weight: 100
  tls:
    termination: passthrough
---
apiVersion: v1
kind: Service
metadata:
  name: fleet-manager-broker-metrics
  namespace: mqtt-broker
  labels:
    application: fleet-manager-broker
    prometheus.io/scrape: 'true'
spec:
  selector:
    ActiveMQArtemis: fleet-manager-broker
  ports:
    - name: metrics
      port: 8161
      targetPort: 8161
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fleet-manager-broker-monitor
  namespace: mqtt-broker
  labels:
    release: prometheus  # match your Prometheus Operator release label
spec:
  selector:
    matchLabels:
      application: fleet-manager-broker
  namespaceSelector:
    matchNames:
      - mqtt-broker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scheme: http
