sites:
  - id: a
    namespace: site-a
    truckCount: 20
  - id: b
    namespace: site-b
    truckCount: 20
  - id: c
    namespace: site-c
    truckCount: 20


brokerHost: mqtt-lb.mqtt-broker.svc.cluster.local
brokerPort: 8883
repoURL: https://github.com/sumicsamy/mqtt.git
image: quay.io/suchugh/fleet-sim:0.0.25
platform: amq
