sites:
  - id: A
    namespace: site-emqx-A
    truckCount: 20
  - id: B
    namespace: site-emqx-B
    truckCount: 20
  - id: C
    namespace: site-emqx-C
    truckCount: 20


brokerHost: emqx-listeners.emqx.svc.cluster.local
brokerPort: 8883
repoURL: https://github.com/sumicsamy/mqtt.git
image: quay.io/suchugh/fleet-sim:0.0.23
platform: emqx