sites:
  - id: alpha
    namespace: site-emqx-alpha
    truckCount: 20
  - id: beta
    namespace: site-emqx-beta
    truckCount: 20
  - id: gamma
    namespace: site-emqx-gamma
    truckCount: 20


brokerHost: emqx-listeners.emqx.svc.cluster.local
brokerPort: 8883
repoURL: https://github.com/sumicsamy/mqtt.git
image: quay.io/suchugh/fleet-sim:0.0.23
platform: emqx