sites:
  - id: pilbara
    namespace: site-emqx-pilbara
    truckCount: 1
  - id: tomprice
    namespace: site-emqx-tomprice
    truckCount: 1
  - id: perth
    namespace: site-emqx-perth
    truckCount: 1


brokerHost: emqx-listeners.emqx.svc.cluster.local
brokerPort: 8883
repoURL: https://github.com/sumicsamy/mqtt.git
image: quay.io/suchugh/fleet-sim:0.0.22
platform: emqx