sites:
  - id: pilbara
    namespace: site-pilbara
    truckCount: 0
  - id: tomprice
    namespace: site-tomprice
    truckCount: 0
  - id: paraburdoo
    namespace: site-paraburdoo
    truckCount: 0


brokerHost: mqtt-lb.mqtt-broker.svc.cluster.local
brokerPort: 8883
repoURL: https://github.com/sumicsamy/mqtt.git
image: quay.io/suchugh/fleet-sim:0.0.25
platform: amq
