apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-telegraf
  namespace: openshift-gitops    # or argocd namespace
spec:
  project: mqtt
  source:
    repoURL: https://github.com/sumicsamy/mqtt.git
    targetRevision: main
    path: telegraf/telegraf
    helm:
      valueFiles:
        - values.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: fleet-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
