{{- if .Values.bridge.enabled }}
{{ range $i, $_ := until (.Values.bridge.replicas | int) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.bridge.mqtt.clientId }}-{{ $i }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $.Values.bridge.mqtt.clientId }}
    clientid: {{ $.Values.bridge.mqtt.clientId }}-{{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Values.bridge.mqtt.clientId }}
      clientid: {{ $.Values.bridge.mqtt.clientId }}-{{ $i }}
  template:
    metadata:
      labels:
        app: {{ $.Values.bridge.mqtt.clientId }}
        clientid: {{ $.Values.bridge.mqtt.clientId }}-{{ $i }}
    spec:
      volumes:
        - name: broker-certs
          secret:
            secretName: {{ $.Values.bridge.mqtt.clientId }}-tls
      containers:
        - name: bridge
          volumeMounts:
            - name: broker-certs
              mountPath: /certs
          image: {{ $.Values.bridge.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MQTT_BROKERS
              value: "{{ $.Values.bridge.mqtt.brokers }}"
            - name: MQTT_TOPIC
              value: "{{ $.Values.bridge.mqtt.topic }}"
            - name: MQTT_QOS
              value: "{{ $.Values.bridge.mqtt.qos }}"
            - name: MQTT_CLIENT_ID
              value: "{{ $.Values.bridge.mqtt.clientId }}-{{ $i }}"
            - name: KAFKA_BROKERS
              value: "{{ $.Values.bridge.kafka.brokers }}"
            - name: KAFKA_TOPIC
              value: "{{ $.Values.bridge.kafka.topic }}"
            - name: KAFKA_CLIENT_ID
              value: "{{ $.Values.bridge.kafka.clientId }}"
            - name: WORKER_COUNT
              value: "{{ $.Values.bridge.workerCount }}"
            - name: MESSAGE_BUFFER
              value: "{{ $.Values.bridge.messageBuffer }}"
            - name: PROM_PORT
              value: "{{ $.Values.bridge.prometheusPort }}"
            - name: MQTT_TLS_CA
              value: "/certs/ca.crt"
            - name: MQTT_TLS_CERT
              value: "/certs/tls.crt"
            - name: MQTT_TLS_KEY
              value: "/certs/tls.key"   
          ports:
            - name: http
              containerPort: 8080
          resources:
{{- toYaml $.Values.bridge.resources | nindent 12 }}
---
{{- end }}
{{- end }}
---
{{- if .Values.bridge.enabled }}
{{ range $i, $_ := until (.Values.bridge.replicas | int)}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.bridge.mqtt.clientId }}-{{ $i }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $.Values.bridge.mqtt.clientId }}
spec:
  type: ClusterIP
  selector:
    clientid: {{ $.Values.bridge.mqtt.clientId }}-{{ $i }}
  ports:
    - name: http
      port: 8080
      targetPort: http
---
{{- end }}
{{- end }}
---
{{- if and .Values.bridge.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.bridge.mqtt.clientId }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $k, $v := .Values.serviceMonitor.labelSelector }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.bridge.mqtt.clientId }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
{{- end }}
