{{- if and (eq .Values.bridge.type "camel") (eq .Values.consumer "aggregator") }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.27.0.redhat-00001
    app.quarkus.io/vcs-uri: https://github.com/sumicsamy/mqtt.git
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: mqtt-kafka-camel
    app.kubernetes.io/part-of: fleet-telemetry
    app.openshift.io/runtime: quarkus
  name: mqtt-kafka-camel
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/part-of: fleet-telemetry
  type: ClusterIP
---
{{ range $index, $_ := until (.Values.bridge.camel.replicas | int)}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.27.0.redhat-00001
    app.quarkus.io/vcs-uri: https://github.com/sumicsamy/mqtt.git
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/part-of: fleet-telemetry
    app.openshift.io/name: mqtt-kafka-camel-{{ $index }}
  name: mqtt-kafka-camel-{{ $index }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt-kafka-camel-{{ $index }}
      app.openshift.io/runtime: quarkus
      app.kubernetes.io/part-of: fleet-telemetry
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        app.quarkus.io/quarkus-version: 3.27.0.redhat-00001
        app.quarkus.io/vcs-uri: https://github.com/sumicsamy/mqtt.git
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/part-of: fleet-telemetry
    spec:
      containers:
        - env:
            - name: MQTT_TLS_CRT
              value: /certs/tls.crt
            - name: MQTT_BROKER_URL
              value: {{ replace "<BROKER>"  ($index|toString) $.Values.bridge.camel.brokerUrl }}
            - name: MQTT_TLS_KEY
              value: /certs/tls.key
            - name: MQTT_TOPIC
              value: {{ $.Values.bridge.mqtt.topic }}
            - name: BRIDGE_ID
              value: {{ $.Values.bridge.mqtt.clientId }}
            - name: KAFKA_TOPIC
              value: {{ $.Values.telemetryTopic.name }}
            - name: KAFKA_BROKERS
              value: {{ $.Values.bridge.kafka.brokers }}
            - name: MQTT_TLS_CA
              value: /certs/ca.crt
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: {{ $.Values.bridge.camel.image }}
          imagePullPolicy: Always
          name: mqtt-kafka-camel
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /certs
              name: mqtt-certs
              readOnly: false
          resources:
{{- toYaml $.Values.bridge.go.resources | nindent 12 }} 
      volumes:
        - name: mqtt-certs
          secret:
            defaultMode: 384
            optional: false
            secretName: {{ $.Values.bridge.mqtt.clientId }}-tls
{{- end }}            
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.27.0.redhat-00001
    app.quarkus.io/vcs-uri: https://github.com/sumicsamy/mqtt.git
  labels:
    app.kubernetes.io/name: mqtt-kafka-camel
    app.kubernetes.io/part-of: fleet-telemetry
    app.openshift.io/runtime: quarkus
  name: mqtt-kafka-camel
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.openshift.io/runtime: quarkus
      app.kubernetes.io/part-of: fleet-telemetry
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}   
  endpoints:
    - scheme: http
      targetPort: 8080
      path: /q/metrics
      interval: 10s
      honorLabels: true
{{- end }}