apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.clusterName }}
  namespace: {{ .Values.namespace }}
spec:
  kafka:
    version: 3.7.0
    metadataMode: unified
---    
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: {{ .Values.namespace }}
spec:
  cluster: {{ .Values.kafka.clusterName }}
  replicas: 3
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 200Gi
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controllers
  namespace: {{ .Values.namespace }}
spec:
  cluster: {{ .Values.kafka.clusterName }}
  replicas: 3
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 50Gi
