apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kafka.clusterName }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
    strimzi.io/kind: Kafka
    strimzi.io/name: {{ .Values.kafka.clusterName }}
data:
  kafka-metrics-config.yaml: |-
    lowercaseOutputName: true
    rules:
      - pattern: 'kafka.server<type=(.+), name=(.+)PerSec\w*><>Count'
        name: kafka_server_$1_$2_total
        type: COUNTER
      - pattern: 'kafka.server<type=(.+), name=(.+)PerSec\w*, topic=(.+)><>Count'
        name: kafka_server_$1_$2_total
        type: COUNTER
        labels:
          topic: "$3"
      - pattern: 'kafka.server<type=(.+), name=(.+)PerSec\w*, topic=(.+), partition=(.*)><>Count'
        name: kafka_server_$1_$2_total
        type: COUNTER
        labels:
          topic: "$3"
          partition: "$4"
      - pattern: 'kafka.network<type=(.+), name=(.+)PerSec\w*><>Count'
        name: kafka_network_$1_$2_total
        type: COUNTER
      - pattern: 'kafka.network<type=RequestMetrics, name=RequestsPerSec, request=(.+)><>Count'
        name: kafka_network_requestspersec_total
        type: COUNTER
        labels:
          request: "$1"
      - pattern: 'kafka.network<type=RequestMetrics, name=TotalTimeMs, request=(.+)><>Histogram\.(\w+)'
        name: kafka_network_request_duration_ms_$2
        type: GAUGE
        labels:
          request: "$1"
      - pattern: 'kafka.network<type=RequestMetrics, name=TotalTimeMs, request=(.+)><>Count'
        name: kafka_network_request_duration_ms_count
        type: COUNTER
        labels:
          request: "$1"
      - pattern: 'kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec, topic=(.+)><>OneMinuteRate'
        name: kafka_server_brokertopicmetrics_messagesin_total_1min
        type: GAUGE
        labels:
          topic: "$1"
      - pattern: 'kafka.server<type=BrokerTopicMetrics, name=BytesInPerSec, topic=(.+)><>OneMinuteRate'
        name: kafka_server_brokertopicmetrics_bytesin_total_1min
        type: GAUGE
        labels:
          topic: "$1"
      - pattern: 'kafka.server<type=BrokerTopicMetrics, name=BytesOutPerSec, topic=(.+)><>OneMinuteRate'
        name: kafka_server_brokertopicmetrics_bytesout_total_1min
        type: GAUGE
        labels:
          topic: "$1"
---
{{- if and .Values.kafkaExporter.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.kafka.clusterName }}-kafka-exporter
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $k, $v := .Values.serviceMonitor.labelSelector }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      strimzi.io/name: {{ .Values.kafka.clusterName }}-kafka
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: tcp-prometheus
      interval: 30s
      path: /metrics
{{- end }}