apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.clusterName }}
  namespace: {{ .Values.namespace }}
spec:
  kafka:

    # REQUIRED for KRaft in 0.46.x
    metadataMode: unified

    # Your listeners as needed
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true

    # KRaft-specific config
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2

  # Optional but usually handy
  entityOperator:
    topicOperator: {}
    userOperator: {}

---    
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/kafka-cluster: {{ .Values.kafka.clusterName }}
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 200Gi
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controllers
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/kafka-cluster: {{ .Values.kafka.clusterName }}
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 50Gi
