---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: fleet-connect
  namespace: {{ .Values.namespace }}
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  logging:
    type: inline
    loggers:
      rootLogger.level: WARN
  version: "4.0.0"       # adjust to your Kafka version
  replicas: {{ .Values.connect.replicas }}
  bootstrapServers: "fleet-kafka-kafka-bootstrap:9092"
  resources:
    requests:
      cpu: {{ .Values.connect.resources.requests.cpu }}
      memory: {{ .Values.connect.resources.requests.memory }}
    limits:
      cpu: {{ .Values.connect.resources.limits.cpu }}
      memory: {{ .Values.connect.resources.limits.memory }}
  build:
    output:   
      type: docker
      image: quay.io/suchugh/fleet-kafka:latest
      pushSecret: suchugh-mqtt-pull-secret
    plugins: 
      - name: mqtt-connector
        artifacts:
          - type: jar
            url: https://github.com/sumicsamy/mqtt/releases/download/v1.0.0/kafka-connect-mqtt-assembly-10.0.3.jar   
  template:
    pod:
      volumes:
      - name: certs-volume
        secret:
          secretName: {{ .Values.bridge.mqtt.clientId }}-tls    
    connectContainer:
      volumeMounts:
        - name: certs-volume
          mountPath: /mnt/certs/ 
          readOnly: true
  config:
    key.converter: {{ .Values.mqttConnector.kafka.keyConverter }}
    value.converter: {{ .Values.mqttConnector.kafka.valueConverter }}
    value.converter.schemas.enable: {{ .Values.mqttConnector.kafka.valueConverterSchemasEnable }}
    group.id: fleet-connect
    offset.storage.topic: connect-offsets
    config.storage.topic: connect-configs
    status.storage.topic: connect-status
    offset.storage.replication.factor: 3
    config.storage.replication.factor: 3
    status.storage.replication.factor: 3

    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: "false"

    # REQUIRED for >100 MB messages:
    producer.max.request.size: 400000000
    producer.buffer.memory: 536870912
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ .Values.mqttConnector.name }}
  namespace: {{ .Values.namespace }}
  metadata:
    labels:
      strimzi.io/cluster: fleet-connect
spec:
  class: io.lenses.streamreactor.connect.mqtt.source.MqttSourceConnector
  tasksMax: {{ .Values.mqttConnector.tasksMax }}
  config:
    connect.mqtt.hosts: "{{ .Values.mqttConnector.mqtt.brokers }}"
    connect.mqtt.topic: "{{ .Values.mqttConnector.mqtt.topicFilter }}"
    connect.mqtt.qos: "{{ .Values.mqttConnector.mqtt.qos }}"
    connect.mqtt.client.id: "{{ .Values.mqttConnector.mqtt.clientId }}"
    topics: "{{ .Values.mqttConnector.kafka.targetTopic }}"
    key.converter: "{{ .Values.mqttConnector.kafka.keyConverter }}"
    value.converter: "{{ .Values.mqttConnector.kafka.valueConverter }}"
    value.converter.schemas.enable: "{{ .Values.mqttConnector.kafka.valueConverterSchemasEnable }}"
    poll.interval.ms: "{{ .Values.mqttConnector.tuning.pollIntervalMs }}"
    producer.override.batch.size: "{{ .Values.mqttConnector.tuning.batchMaxSize }}"
    producer.override.linger.ms: "{{ .Values.mqttConnector.tuning.pollIntervalMs }}"
    connect.mqtt.ssl.ca.cert: /mnt/certs/ca.crt
    connect.mqtt.ssl.cert: /mnt/certs/tls.crt
    connect.mqtt.ssl.key: /mnt/certs/tls.key
    # 🔥 REQUIRED: QoS level (0 recommended for high throughput)
    connect.mqtt.service.quality: "0"

    # 🔥 REQUIRED: KCQL mapping (MQTT → Kafka)
    # FORMAT:
    #   INSERT INTO kafkaTopic SELECT * FROM mqttTopic
    connect.mqtt.kcql: >-
      INSERT INTO truck-telemetry
      SELECT * FROM `mine/fleet/+/truck/+/telemetry`
      WITHFORMAT JSON

    # OPTIONAL - tuning
    poll.interval.ms: "100"
    # producer.override.batch.size: "1000"
    # producer.override.linger.ms: "100"
    producer.override.max.request.size: "400000000"
    producer.override.buffer.memory: "536870912"    
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-offsets
  namespace: fleet-kafka
  labels:
    strimzi.io/cluster: fleet-kafka
spec:
  partitions: 25
  replicas: 3
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-configs
  namespace: fleet-kafka
  labels:
    strimzi.io/cluster: fleet-kafka
spec:
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-status
  namespace: fleet-kafka
  labels:
    strimzi.io/cluster: fleet-kafka
spec:
  partitions: 5
  replicas: 3
  config:
    cleanup.policy: compact


