apiVersion: v1
kind: Secret
metadata:
  name: suchugh-mqtt-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjM1ZqYUhWbmFDdHRjWFIwT2s5SU9WaFRPRkF6UVVZMlUwZFZOazgxU1ZaUFZUSkNPVEZQVjFoTVJrcGFVMVUyV2pCTk4xRkRPRFV6TjBzMVQwcEpOMHRIT0VRNVNUYzNWa2hYUlVFPSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson