apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-user-workload-fleet-metrics
  namespace: grafana
  labels:
    grafana_datasource: 'fleet-metrics'
spec:
  allowCrossNamespaceImport: true
  datasource:
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      tlsSkipVerify: true
    secureJsonData:
      httpHeaderValue1: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJ6SEdvSGduTDdOalQxREo5UTlkY3ZYWGI5a3BleTlWb2J0b3VCamYtb28ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTc2MzM5NjU3NiwiaWF0IjoxNzYzMzkyOTc2LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJqdGkiOiIzYzQ2OWY2Ni01ZTc1LTQ5MzQtOTEyNi00ZjI4NWQxMDE3YmUiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImdyYWZhbmEiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZmxlZXQtbW9uaXRvcmluZy1zYSIsInVpZCI6IjU5YTY0OTlhLTQzOGEtNGViYi05M2U2LTg5NDM2ZjQyMjA0OSJ9fSwibmJmIjoxNzYzMzkyOTc2LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Z3JhZmFuYTpmbGVldC1tb25pdG9yaW5nLXNhIn0.n0b7xec5I_FwEySdwoeiuvm7M2qj9SPwlvFOQJ3Y-JzX2pCscQfNXwHXcZ4C12t2y5zlAF5gC-_BfTQkcPegXG2NQ_4oSdOch8QtLZc8Fyl2_mm89wZsCMX8zTknSuZIkneYcMvj8KDnQGirCgskszfcvzU2UpadXnFv1MK1k87nFRFN311JnBhLl8EyfdnaqWprsX_16OK5JdPqoXx3emijWKcdWzUHudLopevvJZVGNpKXsoULbT3RoeIaGmWCgI40Kc8lioCBMjoboOIFgQIkz-r9G-xhpbL0rWuWie7a6vjRc-U1697O0Mz_wdYEahWSqyBvv0iat2GqrcVOBTSw2K3C9SsYD6FcetC87-2wRsdChsGbx3wdlxNa2TIafawQ0UhP1jfHvDQXHS07MamYQ54gIGcssKoOnAkHFNgSKkNXx7k-sR4yh2QrwIksIWTE4u_sbff_HG4C4yXocAFi67de9FiKNUksFR4i0ZIEGh0VE9gg3rjTuc5N54hlmA3ioGvxnAuq91ElR6uPJXJWGWOTzmDQY02-QAZGMlYwBZHpubhz1h961FiEfospStp4MD-tvOXK1gNfp0HAz0HFUs3D5SbXC7oJ3ytxfxfnfDVhgC1ZRAiiWq_2OIEnlSKfKt2pjMZ6v3x1iWNq4ym2DaVLYzXV_rrdly67hBE"
    type: prometheus
    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  instanceSelector:
    matchLabels:
      dashboards: fleet-metrics
  plugins:
    - name: grafana-clock-panel
      version: 1.3.0
  resyncPeriod: 10m0s