apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-user-workload-fleet-metrics
  namespace: grafana
  labels:
    grafana_datasource: 'fleet-metrics'
spec:
  allowCrossNamespaceImport: true
  datasource:
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      tlsSkipVerify: true
    secureJsonData:
      httpHeaderValue1: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRHMHZia1FXMDBfVl9PcVhKVFkyTVlBM21BR2lRcVFmaGR3amU3WVIxQkUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTc5NDIxNzgxNiwiaWF0IjoxNzYyNjgxODE2LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJqdGkiOiI5Y2UyNDM4Yy1hNTU1LTQ2NDctOGFlZi00YWQ1MGJjMDIzZGIiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImdyYWZhbmEiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZmxlZXQtbW9uaXRvcmluZy1zYSIsInVpZCI6Ijg3NjkxMGEzLTA0MzktNGQzYi04YWJhLTA3M2M2MzcxMGNlOSJ9fSwibmJmIjoxNzYyNjgxODE2LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Z3JhZmFuYTpmbGVldC1tb25pdG9yaW5nLXNhIn0.hfYpquXjDyLx4S4vyaWj2-cvmrk9Plcu8yomdPXNy_-_mqlwUp5KVyYgkCUahMDYUEsAIvn4dt2fsBZBAqloomUrFMQhuUF0eeG-7jEub9KF8ulYW14Z9_bM8n7vcjMkIpSRQl8MHzRWzBunhxpLOdqKCNQbdbg3MrZEsa-oc6ZWSHKfOMzDI1RYYbynAAJRKD_iEPzRsKj90DPeK_fZXO8CusbALltews7giJmp7YGMRYKhN4x9hejqW_dYl5w-EAzaNxhrLs74Gg6NGMGTpm2BsSH0zrAoxbYI7PZyu67ztNz5AQbeNYDBVuyDyvEqsWJlUMBDUo93e9yLEp8d90QaLIc4aU_0U_mn4LDKmlONE2gwjKGfyPE3jxHwAm1TNVtd3tLk7Ng9X8AuCf_FEiIJcleKemycCqb-3yQ2I5IsSisN8L5B02nzdIm_309SK-B4Kp-JHsIEmVtRbb9nC1TM9xf50mE2MofJSZlJRwuNe1QmKZAQHO8ygOIDRTNJ0DLTW-IgGitUT4Ek5hqPMF7OmT2XSf-vNbGOZR6j4IsgBJSt6GcO2kbh4Owkngh_5VnCYDTjcJ051fYuv_TeTk6se_3tvGT1BF-oPJcXhZWQI1nlAXn9NT3tPBebq8_tqEXApn4cnVHmNeW8XX2eQdq6Qpzvt7MIEknF3L1SN-4"
    type: prometheus
    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  instanceSelector:
    matchLabels:
      dashboards: fleet-metrics
  plugins:
    - name: grafana-clock-panel
      version: 1.3.0
  resyncPeriod: 10m0s