apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    dashboards: fleet-metrics
    folders: fleet-metrics
  name: fleet-monitoring
  namespace: grafana
spec:
  version: docker.io/grafana/grafana@sha256:e0b95a0e84e14c3d1ba32c658c4756fcf9b83a43013c8de9eacc05d40af19a5c
  config:
    auth:
      disable_login_form: 'false'
      disable_signout_menu: 'false'
    log:
      level: info
      mode: console
    security:
      admin_password: start
      admin_user: root
  route:
    spec:
      tls:
        termination: edge
      to:
        kind: Service
        name: fleet-monitoring-service
        weight: 100
  serviceAccount:
    metadata:
      annotations:
        serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"fleet-monitoring-route"}}'
      
---
apiVersion: v1
kind: Secret
metadata:
  name: fleet-monitoring-sa-token
  namespace: grafana
  annotations:
    kubernetes.io/service-account.name: fleet-monitoring-sa
type: kubernetes.io/service-account-token        