apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-mqtt
  namespace: openshift-gitops
spec:
  project: mqtt
  source:
    repoURL: 'https://github.com/sumicsamy/mqtt.git'
    targetRevision: main
    path: cert-manager/mgr/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=false
        - PruneLast=true

