apiVersion: v1
kind: Secret
metadata:
  name: fleet-ca-bundle
  namespace: mqtt-broker
type: Opaque
stringData:
  ca.crt: |
    # fleet root CA
    {{  (lookup "v1" "Secret" "mqtt-broker" "fleet-root-ca").data.ca.crt | b64dec  }}
    # pilbara root CA
    {{  (lookup "v1" "Secret" "site-pilbara" "site-pilbara-root-ca").data.ca.crt | b64dec  }}
    # tomprice root CA
    {{  (lookup "v1" "Secret" "site-tomprice" "site-tomprice-root-ca").data.ca.crt | b64dec  }}
