apiVersion: v1
kind: Secret
metadata:
  name: amq-jaas-cert-login
  namespace: {{ .Values.brokerNamespace }}
stringData:
  login.config: |
    CertLogin {
        org.apache.activemq.artemis.spi.core.security.jaas.TextFileCertificateLoginModule
            debug=true
            reload=true
            org.apache.activemq.jaas.textfiledn.user="artemis-certs.properties"
            org.apache.activemq.jaas.textfiledn.role="artemis-roles.properties";
    };
    console {
        org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
            debug=true
            reload=true
            org.apache.activemq.jaas.properties.user="artemis-certs.properties"
            org.apache.activemq.jaas.properties.role="artemis-roles.properties";

        org.apache.activemq.artemis.spi.core.security.jaas.GuestLoginModule sufficient
            debug=false
            org.apache.activemq.jaas.guest.user="admin"
            org.apache.activemq.jaas.guest.role="admin";
    };

  artemis-certs.properties: |
    {{- range $site := .Values.sites }}
    {{- range $i, $_ := until ($site.truckCount | int) }}
    truck-{{ $site.id }}-{{ printf "%03d" $i }}=CN=truck-{{ $site.id }}-{{ printf "%03d" $i }}
    {{- end }}
    {{- end }}

  artemis-roles.properties: |
    users=
    {{- range $site := .Values.sites }}
    {{- range $i, $_ := until ($site.truckCount | int) }}
    truck-{{ $site.id }}-{{ printf "%03d" $i }},
    {{- end }}
    {{- end }}
