apiVersion: v1
kind: Secret
metadata:
  name: amq-jaas-cert-login
  namespace: {{ .Values.brokerNamespace }}
stringData:
  login.config: |
    activemq {
      org.apache.activemq.artemis.spi.core.security.jaas.TextFileCertificateLoginModule required
      debug=true
      org.apache.activemq.artemis.spi.core.security.jaas.TextFileCertificateLoginModule.verifyDN=true
      org.apache.activemq.artemis.spi.core.security.jaas.TextFileCertificateLoginModule.usersFile="/amq/extra/secrets/amq-jaas-cert-login/artemis-certs.properties"
      org.apache.activemq.artemis.spi.core.security.jaas.TextFileCertificateLoginModule.rolesFile="/amq/extra/secrets/amq-jaas-cert-login/artemis-roles.properties";
    };
    console {
    org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
        debug=false
        reload=true
        org.apache.activemq.jaas.properties.user="artemis-users.properties"
        org.apache.activemq.jaas.properties.role="artemis-roles.properties";

    org.apache.activemq.artemis.spi.core.security.jaas.GuestLoginModule sufficient
        debug=false
        org.apache.activemq.jaas.guest.user="admin"
        org.apache.activemq.jaas.guest.role="admin";
    };

  artemis-certs.properties: |
    {{- range $site := .Values.sites }}
    {{- range $i, $_ := until ($site.truckCount | int) }}
    CN=truck-{{ $site.id }}-{{ printf "%03d" $i }}
    {{- end }}
    {{- end }}

  artemis-roles.properties: |
    {{- range $site := .Values.sites }}
    {{- range $i, $_ := until ($site.truckCount | int) }}
    truck-{{ $site.id }}-{{ printf "%03d" $i }}
    {{- end }}
    {{- end }}
