apiVersion: v1
kind: Secret
metadata:
  name: site-roles-bp
  namespace: {{ .Values.brokerNamespace }}
type: Opaque
stringData:
  site-roles.properties: |
{{- range $site := .Values.sites }}
  {{- range $i, $v := until ($site.truckCount | int) }}
    securityRoles."mine.fleet.{{ $site.id }}.truck.{{ printf "%03d" $i }}.telemetry".truck-{{ $site.id }}-{{ printf "%03d" $i }}.send=true
    securityRoles."mine.fleet.{{ $site.id }}.truck.{{ printf "%03d" $i }}.telemetry".truck-{{ $site.id }}-{{ printf "%03d" $i }}.createAddress=true
  {{- end }}
{{- end }}
    securityRoles.#.telegraf.consume=true
    securityRoles.#.telegraf.browse=true
    securityRoles.#.admin.consume=true
    securityRoles.#.admin.send=true
    securityRoles.#.admin.consume=true
    securityRoles.#.admin.createAddress=true
    securityRoles.#.admin.deleteAddress=true
    securityRoles.#.admin.manageRoles=true
    securityRoles.#.admin.manageUsers=true
