apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: emqx
  namespace: openshift-gitops
spec:
  description: Project to install emqx broker
  sourceRepos:
    - 'https://github.com/sumicsamy/mqtt.git'
    - 'https://repos.emqx.io/charts' 
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
