apiVersion: v1
kind: Namespace
metadata:
  name: fleet-metrics
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
--- 
{{- range $i, $v := until (.Values.size | int) }}  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-{{ $i }}
  namespace: fleet-metrics
  labels:
    app: telegraf-{{ $i }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: telegraf-{{ $i }}
  template:
    metadata:
      labels:
        app: telegraf-{{ $i }}
    spec:
      containers:
      - name: telegraf
        image: docker.io/library/telegraf:1.33
        imagePullPolicy: IfNotPresent
        ports:
          - name: metrics
            containerPort: 9273
        volumeMounts:
          - name: config
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf.conf
          - name: certs
            mountPath: /certs
 
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "1Gi"
      volumes:
        - name: config
          configMap:
            name: telegraf-config-{{ $i }}
        - name: certs
          secret:
            secretName: telegraf-tls       
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-{{ $i }}
  namespace: fleet-metrics
  labels:
    app: telegraf-{{ $i }}
spec:
  selector:
    app: telegraf-{{ $i }}
  ports:
    - name: metrics
      port: 9273
      targetPort: 9273
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: telegraf-{{ $i }}
  namespace: fleet-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: telegraf-{{ $i }}
  endpoints:
    - port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - fleet-metrics
---      
{{- end  }}      