{{- $groups := .Values.sharedGroups | default (list "telegraf-g1" "telegraf-g2" "telegraf-g3") -}}
{{- $gCount := len $groups -}}

{{- range $i, $_ := until (.Values.size | int) }}
{{- $group := index $groups (mod $i $gCount) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: telegraf-config-{{ $i }}
  namespace: fleet-metrics
data:
  telegraf.conf: |
    [agent]
      interval = "100ms"
      flush_interval = "100ms"
      metric_buffer_limit = 8000000     # bump for high throughput
      round_interval = false
      debug = false
      quiet = true

    [[inputs.mqtt_consumer]]
      tls_ca = "/certs/ca.crt"
      tls_cert = "/certs/tls.crt"
      tls_key = "/certs/tls.key"
      servers = ["ssl://mqtt-lb.mqtt-broker.svc.cluster.local:8883"]
      qos = 1
      max_undelivered_messages = 8000000
      persistent_session = true
      insecure_skip_verify = true

      # each Telegraf instance gets a unique client_id and one shared group
      client_id = "telegraf-{{ $group }}-{{ $i }}"
      topics = ["$share/{{ $group }}/mine/fleet/+/truck/+/telemetry"]

      data_format = "json_v2"

      [[inputs.mqtt_consumer.json_v2]]
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "spd"        type = "float"
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "eng.rpm"    type = "int"
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "eng.tmp"    type = "float"
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "eng.fuel"   type = "float"
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "load.pay_t" type = "float"
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "sys.cpu"    type = "int"
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "sys.tmp"    type = "float"
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "loc.lat"    type = "float"
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "loc.lon"    type = "float"
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "loc.alt"    type = "float"

        [[inputs.mqtt_consumer.json_v2.tag]]
          path = "truck"
        [[inputs.mqtt_consumer.json_v2.tag]]
          path = "region"

    [[outputs.prometheus_client]]
      listen = ":9273"
      metric_version = 2
      path = "/metrics"
      expiration_interval = "0s"

    [[outputs.file]]
      files = ["stdout"]
      data_format = "json"
---
{{- end }}
