# --------------------------------------------------------------------
#  Application Default Config
# --------------------------------------------------------------------
bridge.id=mqtt-kafka-camel-01
# TLS UPDATE: Changed protocol to ssl:// and port to 8883
mqtt.broker.url=ssl://mqtt-lb.mqtt-broker.svc.cluster.local:8883
mqtt.topic=mine/fleet/+/truck/+/#
mqtt.tls.ca=/certs/ca.crt
mqtt.tls.crt=/certs/tls.crt
mqtt.tls.key=/certs/tls.key

kafka.brokers=my-cluster-kafka-bootstrap:9092
kafka.topic=truck-telemetry

# --------------------------------------------------------------------
#  OpenShift / Kubernetes Generation
# --------------------------------------------------------------------
quarkus.container-image.builder=openshift
quarkus.openshift.part-of=fleet-telemetry
quarkus.openshift.route.expose=false
quarkus.kubernetes-client.trust-certs=true

# --------------------------------------------------------------------
#  Environment Variables (Mapped to Deployment)
# --------------------------------------------------------------------
# TLS UPDATE: Updated default URL and added Truststore Env Vars
quarkus.openshift.env.vars.MQTT_BROKER_URL=ssl://mqtt-broker:8883
quarkus.openshift.env.vars.MQTT_TOPIC=$share/camelgroup/mine/fleet/+/truck/+/#

quarkus.openshift.env.vars.KAFKA_BROKERS=my-cluster-kafka-bootstrap:9092
quarkus.openshift.env.vars.KAFKA_TOPIC=truck-telemetry
quarkus.openshift.env.vars.BRIDGE_ID=camel-mqtt-bridge-01
quarkus.openshift.env.vars.MQTT_TLS_CA=/certs/ca.crt
quarkus.openshift.env.vars.MQTT_TLS_CRT=/certs/tls.crt
quarkus.openshift.env.vars.MQTT_TLS_KEY=/certs/tls.key

quarkus.openshift.mounts.mqtt-certs.path=/deployments/certs
quarkus.openshift.secret-volumes.mqtt-certs.secret-name=mqtt-bridge-certs

# --------------------------------------------------------------------
#  Quarkus & Metrics
# --------------------------------------------------------------------
quarkus.micrometer.export.prometheus.enabled=true
camel.health.enabled=true