sites:
  - id: pilbara
    namespace: site-pilbara
    truckCount: 100
  - id: tomprice
    namespace: site-tomprice
    truckCount: 100
  - id: paraburdoo
    namespace: site-paraburdoo
    truckCount: 100
brokerNamespace: mqtt-broker    

broker:
  replicas: 2
  clustered: false
  persistence:
    enabled: false
    size: 200Gi
  resources:
    requests:
      memory: 32Gi
      cpu: "2000m"
    limits:
      memory: "64Gi"
      cpu: "6000m"  