sites:
  - id: A
    namespace: site-A
    truckCount: 100
  - id: B
    namespace: site-B
    truckCount: 100
  - id: C
    namespace: site-C
    truckCount: 100
brokerNamespace: mqtt-broker    

broker:
  replicas: 2
  clustered: false
  persistence:
    enabled: false
    size: 200Gi
  resources:
    requests:
      memory: 32Gi
      cpu: "2000m"
    limits:
      memory: "64Gi"
      cpu: "6000m"  