sites:
  - id: a
    namespace: site-alpha
    truckCount: 100
  - id: b
    namespace: site-beta
    truckCount: 100
brokerNamespace: mqtt-broker    

broker:
  replicas: 2
  clustered: false
  persistence:
    enabled: false
    size: 200Gi
  resources:
    requests:
      memory: 32Gi
      cpu: "2000m"
    limits:
      memory: "64Gi"
      cpu: "6000m"  