---    
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: fleet-manager-broker
  namespace: {{ .Values.brokerNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  adminUser: admin
  adminPassword: admin
  acceptors:
    - name: mqtts
      protocols: mqtt
      port: 8883
      sslEnabled: true
      needClientAuth: true
      verifyHost: false
      sslSecret: amq-broker-tls
      trustSecret: fleet-root-trust
      suppressInternalManagementObjects: true
      trustStoreType: PEMCA
      sslProvider: OPENSSL
      enabledProtocols: TLSv1.2,TLSv1.3
      enabledCipherSuites: TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384
      defaultConsumerWindowSize: 
  addressSettings:
    addressSetting:
    - match: "mine.fleet.#"
      maxSizeBytes: -"1"
      pageSizeBytes: "104857600"
      addressFullPolicy: DROP
      maxDeliveryAttempts: 1
      redeliveryDelay: 0
      enableMetrics: true
      defaultConsumerWindowSize: 104857600
      deadLetterAddress: "DLQ"
      autoCreateQueues: true
      autoCreateAddresses: true
      autoDeleteQueues: false
      autoDeleteAddresses: false
    - match: "$.artemis.internal.#"
      maxSizeBytes: "10485760"
      addressFullPolicy: PAGE   
  brokerProperties:
    - "acceptorConfigurations.mqtts.params.sslAutoReload=true"
    - brokerPlugins.\"org.apache.activemq.artemis.core.server.plugin.impl.LoggingActiveMQServerPlugin.class\".init=LOG_CONNECTION_EVENTS=false,LOG_SESSION_EVENTS=false,LOG_CONSUMER_EVENTS=true
    - "acceptorConfigurations.mqtts.params.directDeliver=false"
    - "acceptorConfigurations.mqtts.params.batchDelay=5"
    - globalMaxSize=-1
    - journalSyncNonTransactional=false
    - journalBufferTimeout_AIO=20000
    - journalBufferSize_AIO=20971520
    - journalMinFiles=10
    - journalPoolFiles=50
    

  env:
    - name: TZ
      value: Australia/Melbourne
    - name: JDK_JAVA_OPTIONS
      value: -XshowSettings:system
    - name: JAVA_ARGS_APPEND
      value: > 
        -Dhawtio.realm=console
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=50
        -Djava.nio.channels.spi.SelectorProvider=sun.nio.ch.EPollSelectorProvider
        -Damq.security=true  
  deploymentPlan:
    size: {{ .Values.broker.replicas }}
    persistenceEnabled: {{ .Values.broker.persistence.enabled }}
    clustered: {{ .Values.broker.clustered }}
    journalType: aio
    enableMetricsPlugin: true
    storage:
      size: {{ .Values.broker.persistence.size }}
    extraMounts:
      secrets:
      - "fleet-manager-broker-jaas-config"
      - "site-roles-bp"
    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #           matchExpressions:
    #             - key: ActiveMQArtemis
    #               operator: In
    #               values:
    #                 - fleet-manager-broker
    #         topologyKey: kubernetes.io/hostname
  console:
    expose: true
  