apiVersion: v1
kind: Secret
metadata:
  name: fleet-manager-broker-jaas-config
  namespace: {{ .Values.brokerNamespace }}
stringData:
  login.config: |
    activemq {
      org.apache.activemq.artemis.spi.core.security.jaas.TextFileCertificateLoginModule optional
          debug=true
          reload=true
          verifyDN=false
          org.apache.activemq.jaas.textfiledn.user="artemis-certs.properties"
          org.apache.activemq.jaas.textfiledn.role="artemis-roles.properties";

      org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
          debug=false
          reload=true
          org.apache.activemq.jaas.properties.user="artemis-users.properties"
          org.apache.activemq.jaas.properties.role="artemis-roles.properties";

      org.apache.activemq.artemis.spi.core.security.jaas.GuestLoginModule optional
          debug=false
          org.apache.activemq.jaas.guest.user="admin"
          org.apache.activemq.jaas.guest.role="admin";
    };
    console {
      org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
          debug=false
          reload=true
          org.apache.activemq.jaas.properties.user="artemis-users.properties"
          org.apache.activemq.jaas.properties.role="artemis-roles.properties";

      org.apache.activemq.artemis.spi.core.security.jaas.GuestLoginModule optional
          debug=true
          org.apache.activemq.jaas.guest.user="admin"
          org.apache.activemq.jaas.guest.role="admin";
    };

  artemis-certs.properties: |
    {{- range $site := .Values.sites }}
    {{- range $i, $_ := until ($site.truckCount | int) }}
    truck-{{ $site.id }}-{{ printf "%03d" $i }}=CN=truck-{{ $site.id }}-{{ printf "%03d" $i }}
    {{- end }}
    {{- end }}
    telegraf=CN=telegraf.fleet-metrics.svc.cluster.local
    mqtt-kafka-bridge=CN=mqtt-kafka-bridge.fleet-kafka.svc.cluster.local
    mqtt-consumer=CN=mqtt-consumer.mqtt-perf.svc.cluster.local
    mqtt-consumer=CN=mqtt-consumer

  artemis-roles.properties: |
    {{- range $site := .Values.sites }}
    {{- range $i, $_ := until ($site.truckCount | int) }}
    truck-{{ $site.id }}-{{ printf "%03d" $i }}=truck-{{ $site.id }}-{{ printf "%03d" $i }}
    {{- end }}
    {{- end }}
    telegraf=telegraf
    admin=admin
    mqtt-kafka-bridge=mqtt-kafka-bridge
    mqtt-consumer=mqtt-consumer

  artemis-users.properties: |
    admin = admin