FROM golang:1.25 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o mqtt-consumer main.go

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/mqtt-consumer /mqtt-consumer
EXPOSE 8080
ENTRYPOINT ["/mqtt-consumer"]
