apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-sim-apps
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sumicsamy/mqtt.git
    targetRevision: main
    path: fleet_sim/argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Child Applications (sites)
  sources:
    - repoURL: https://github.com/sumicsamy/mqtt.git
      path: fleet_sim/overlays/pilbara
      targetRevision: main
    - repoURL: https://github.com/sumicsamy/mqtt.git
      path: fleet_sim/overlays/tomprice
      targetRevision: main
