FROM golang:1.25 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o amqp-kafka-bridge main.go

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/amqp-kafka-bridge /amqp-kafka-bridge
EXPOSE 8080
ENTRYPOINT ["/amqp-kafka-bridge"]