apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt-openshift-app
  namespace: argocd
spec:
  project: mqtt
  source:
    # Replace with your Git repo URL. Path points to the openshift manifest in the parent repo's k8s folder.
    repoURL: "https://github.com/sumicsamy/mqtt.git"
    targetRevision: main
    path: "../k8s/openshift.yml"
  destination:
    # Deploy to the in-cluster API server; change to the target cluster URL if deploying remotely.
    server: "https://kubernetes.default.svc"
    # Namespace in the target cluster where the resources from openshift.yml will be applied.
    namespace: fleet-kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false