{{- range $site := .Values.sites }}
{{- if eq $.Values.platform "amq" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fleet-sim-pod-monitor
  namespace: {{ $site.namespace }}
  labels:
    fleet_sim: "true"
spec:
  selector:
    matchLabels:
      fleet_sim: "true"
  podMetricsEndpoints:
  - path: /metrics
    port: http-metrics
---
{{- else }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fleet-sim-pod-monitor
  namespace: {{ $site.namespace }}
  labels:
    fleet_sim: "true"
spec:
  selector:
    matchLabels:
      fleet_sim: "true"
  podMetricsEndpoints:
  - path: /metrics
    port: http-metrics
{{- end }}
{{- end }}