{{- if eq .Values.platform "amq" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fleet-sim-pod-monitor
  labels:
    fleet_sim: "true"
spec:
  selector:
    matchLabels:
      fleet_sim: "true"
  namespaceSelector:
    matchNames:
      - site-pilbara
      - site-tomprice
      - site-paraburdoo
  podMetricsEndpoints:
  - path: /metrics
    port: http-metrics
---
{{- else }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fleet-sim-pod-monitor
  labels:
    fleet_sim: "true"
spec:
  selector:
    matchLabels:
      fleet_sim: "true"
  namespaceSelector:
    matchNames:
      - site-emqx-pilbara
      - site-emqx-tomprice
      - site-emqx-paraburdoo
  podMetricsEndpoints:
  - path: /metrics
    port: http-metrics
{{- end }}
