apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: telegraf-tls
  namespace: fleet-metrics
spec:
  secretName: telegraf-tls
  commonName: telegraf.fleet-metrics.svc.cluster.local
  usages: ["client auth"]
  issuerRef:
    name: fleet-issuer
    kind: ClusterIssuer