apiVersion: v1
kind: Namespace
metadata:
  name: fleet-metrics
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: fleet-metrics
  labels:
    app: telegraf
spec:
  replicas: 25
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: docker.io/library/telegraf:1.31
        imagePullPolicy: IfNotPresent
        ports:
          - name: metrics
            containerPort: 9273
        volumeMounts:
          - name: config
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf.conf
          - name: certs
            mountPath: /certs
 
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "4Gi"
      volumes:
        - name: config
          configMap:
            name: telegraf-config
        - name: certs
          secret:
            secretName: telegraf-tls       
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  namespace: fleet-metrics
  labels:
    app: telegraf
spec:
  selector:
    app: telegraf
  ports:
    - name: metrics
      port: 9273
      targetPort: 9273
