apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: telegraf-consumer-hpa
  namespace: fleet-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: telegraf
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 120
