apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: telegraf-metrics
  namespace: fleet-metrics
  labels:
    release: prometheus-user-workload
spec:
  selector:
    matchLabels:
      app: telegraf
  endpoints:
    - port: metrics
      interval: 15s
