[agent]
  interval = "5s"
  flush_interval = "5s"
  hostname = "telegraf"
  round_interval = true

[[inputs.mqtt_consumer]]
  servers = ["ssl://mqtt-lb.mqtt-broker.svc.cluster.local:8883"]
  topics  = ["mine/fleet/+/truck/+/telemetry"]
  qos = 1
  client_id = "telegraf-mqtt"
  insecure_skip_verify = true
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "spd"        type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "eng.rpm"    type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "eng.tmp"    type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "eng.fuel"   type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "load.pay_t" type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "sys.cpu"    type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "sys.tmp"    type = "float"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "truck"
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "region"

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
  path = "/metrics"
