sites:
  - id: pilbara
    namespace: site-pilbara
    truckCount: 100
  - id: tomprice
    namespace: site-tomprice
    truckCount: 100



brokerHost: mqtt-lb.mqtt-broker.svc.cluster.local
brokerPort: 8883
repoURL: https://github.com/sumicsamy/mqtt.git
image: quay.io/suchugh/fleet-sim:0.0.13
brokerNamespace: mqtt-broker