FROM golang:1.25 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o fleet-aggregator main.go

FROM alpine:3.22
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/fleet-aggregator /fleet-aggregator
CMD ["/fleet-aggregator"]
